### ISSUE TITLE
[Enhancement] Custom parameters for each different pokémon

### ISSUE THREAD

**Issue by Lebeg134** [Fly33/fly33.github.io#1]
Hey, I made a tool where you can use brackets() in your Pokémon Go searches. It would bee cool if we could integrate our tools together.
If you could generate something like:
`(mon1&tag1&tag2&tag3),(mon2,mon3,mon4&tag4,tag5,tag6)&globaltag1&!globaltag2`
My code can convert it into a in-game usable form:
`mon2,mon3,mon4,mon1&mon2,mon3,mon4,tag1&mon2,mon3,mon4,tag2&mon2,mon3,mon4,tag3&tag4,tag5,tag6,mon1&tag4,tag5,tag6,tag1&tag4,tag5,tag6,tag2&tag4,tag5,tag6,tag3&globaltag1&!globaltag2`
This can be pasted into the game and does actually work.
https://github.com/Lebeg134/MonGoSearch
My project is a cross platform Flutter project, meaning it can complie to JS
You can also try out my tool at:
https://mongo.lebeg134.hu/

**Comment by Fly33** [comment]
Hi. Thank you for the suggestion but it already have all functionality you have. You can paste any Pokemon Go filter into the text area and it will be parsed and converted to my format. Although it doesn't support brackets now it supported that in early days and it was removed as unnecessary.

**Comment by Lebeg134** [comment]
I understand.
I really like the work you have done, and would like to continue to work on my project.
Can I use some aspects of your work?
Such as: 

- Leaving some text in the search as a watermark (I would never came up with this myself, its genius btw)
- The idea of using Serebii icons
- Some of your collected language data. ( I could collect this myself but would make things easier)

I wouldn't actually use any of your code.

Of course I would give credit to you and would post your donation link in the footer or the information part of my app (if I ever release an app xD)

**Comment by Fly33** [comment]
You may use anything you want. See MIT license description for clarification. And Serebii icons belongs to Serebii. The language data was retreived from Pokemon GO apk.
